framework:
    rate_limiter:
        login_failure:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'

        password_change:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'
